name: Code CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: build-ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:

  windows-tcc:
    runs-on: windows-2019
    timeout-minutes: 121
    env:
      VFLAGS: -cc tcc -no-retry-compilation
      VJOBS: 1
      VTEST_SHOW_START: 1
      VERBOSE_MAKE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build with make.bat -tcc
        run: |
          .\make.bat -tcc
      - name: Install dependencies
        run: |
          .\v.exe setup-freetype
          .\.github\workflows\windows-install-sqlite.bat
      - name: v doctor
        run: |
          ./v doctor
      - name: Make sure running TCC64 instead of TCC32
        run: ./v test .github\workflows\make_sure_ci_run_with_64bit_compiler_test.v
      - name: Verify `v test` works
        run: |
          .\v.exe cmd/tools/test_if_v_test_system_works.v
          .\cmd\tools\test_if_v_test_system_works.exe
      - name: Verify `v vlib/v/gen/c/coutput_test.v` works
        run: |
          .\v.exe vlib/v/gen/c/coutput_test.v
      - name: Self tests
        run: ./v test-self
      - name: Test ./v doc -v clipboard *BEFORE building tools*
        run: ./v doc -v clipboard
      - name: Test v build-tools
        run: ./v -W build-tools
      - name: Test ./v doc clipboard
        run: ./v doc clipboard
      - name: Test v->js
        run: ./v -o hi.js examples/hello_v_js.v && node hi.js
      - name: Test v binaries
        run: ./v build-vbinaries
      - name: Build examples
        run: ./v build-examples
      - name: v2 self compilation
        run: .\v.exe -o v2.exe cmd/v && .\v2.exe -o v3.exe cmd/v
