name: CI Linux

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/linux_ci.yml'
      - 'cmd/tools/**'
      - '!cmd/tools/builders/**.v'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/linux_ci.yml'
      - 'cmd/tools/**'
      - '!cmd/tools/builders/**.v'

jobs:
  check-error-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      VFLAGS: -cc tcc -no-retry-compilation
    steps:
      - name: Show custom error
        run: echo '::error file=./vlib/flag/flag_test.v,line=98::this is a custom error message'
      - name: Show custom warning
        run: echo '::warning file=./vlib/flag/flag_test.v,line=7::this is a custom warning message'
      - name: Show custom notice
        run: echo '::notice file=./vlib/flag/flag_test.v,line=60::this is a custom notice message'

      - name: Show custom error file url
        run: echo '::error file=https://github.com/vlang/v/blob/master/vlib/flag/flag_test.v,line=98::this is a custom error message 2'
      - name: Show custom warning file url
        run: echo '::warning file=https://github.com/vlang/v/blob/master/vlib/flag/flag_test.v,line=7::this is a custom warning message 2'
      - name: Show custom notice file url
        run: echo '::notice file=https://github.com/vlang/v/blob/master/vlib/flag/flag_test.v,line=60::this is a custom notice message 2'

      - name: Show custom error title
        run: echo '::error file=./vlib/flag/flag_test.v,line=98,title=vlib/flag/flag_test.v::this is a custom error message 3'
      - name: Show custom warning title
        run: echo '::warning file=./vlib/flag/flag_test.v,line=7,title=vlib/flag/flag_test.v::this is a custom warning message 3'
      - name: Show custom notice title
        run: echo '::notice file=./vlib/flag/flag_test.v,line=60,title=vlib/flag/flag_test.v::this is a custom notice message 3'

      - name: Show custom error content url
        run: echo "::error file=vlib/flag/flag_test.v,line=98::emessage 4 https://github.com/vlang/v/blob/$GITHUB_SHA/vlib/flag/flag_test.v#L98"
      - name: Show custom warning content url
        run: echo "::warning file=vlib/flag/flag_test.v,line=7::wmessage 4 https://github.com/vlang/v/blob/$GITHUB_SHA/vlib/flag/flag_test.v#L7"
      - name: Show custom notice content url
        run: echo "::notice file=vlib/flag/flag_test.v,line=60::nmessage 4 https://github.com/vlang/v/blob/$GITHUB_SHA/vlib/flag/flag_test.v#L60"

      - name: Show custom error content url 44
        run: echo "::error file=vlib/flag/flag_test.v,line=98::emessage 44 https://github.com/vlang/v/blob/${GITHUB_SHA}/vlib/flag/flag_test.v#L98"
      - name: Show custom warning content url 44
        run: echo "::warning file=vlib/flag/flag_test.v,line=7::wmessage 44 https://github.com/vlang/v/blob/${GITHUB_SHA}/vlib/flag/flag_test.v#L7"
      - name: Show custom notice content url 44
        run: echo "::notice file=vlib/flag/flag_test.v,line=60::nmessage 44 https://github.com/vlang/v/blob/${GITHUB_SHA}/vlib/flag/flag_test.v#L60"

      - name: Show custom error content url 444
        run: |
          echo -ne "::error file=vlib/flag/flag_test.v,line=98::emessage 444 https://github.com/vlang/v/blob/${GITHUB_SHA}/vlib/flag/flag_test.v#L98 abc\nline 2\n"
          echo -ne "::warning file=vlib/flag/flag_test.v,line=7::wmessage 444 https://github.com/vlang/v/blob/${GITHUB_SHA}/vlib/flag/flag_test.v#L7 def\nline 2\n"
          echo -ne "::notice file=vlib/flag/flag_test.v,line=60::nmessage 444 https://github.com/vlang/v/blob/${GITHUB_SHA}/vlib/flag/flag_test.v#L60 xyz\nline 2\n"

      - name: Show custom error content url 4441
        run: |
          echo -ne "::error file=vlib/flag/flag_test.v,line=98::https://github.com/vlang/v/blob/${GITHUB_SHA}/vlib/flag/flag_test.v#L98 abc\nline2\n"
          echo -ne "::warning file=vlib/flag/flag_test.v,line=7::https://github.com/vlang/v/blob/${GITHUB_SHA}/vlib/flag/flag_test.v#L7 def\nline2\n"
          echo -ne "::notice file=vlib/flag/flag_test.v,line=60::https://github.com/vlang/v/blob/${GITHUB_SHA}/vlib/flag/flag_test.v#L60 xyz\nline2\n"

      - name: Generate list using Markdown
        run: |
          echo "GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY"
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY

      - name: Show custom error content rel url
        run: echo '::error file=vlib/flag/flag_test.v,line=98::this is a custom error message 5 [a relative link](/vlib/flag/flag_test.v#L98)'
      - name: Show custom warning content url
        run: echo '::warning file=vlib/flag/flag_test.v,line=7::this is a custom warning message 5 [a relative link](/vlib/flag/flag_test.v#L7)'
      - name: Show custom notice content url
        run: echo '::notice file=vlib/flag/flag_test.v,line=60::this is a custom notice message 5 [a relative link](/vlib/flag/flag_test.v#L60)'
