name: CI Linux

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/linux_ci.yml'
      - 'cmd/tools/**'
      - '!cmd/tools/builders/**.v'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/linux_ci.yml'
      - 'cmd/tools/**'
      - '!cmd/tools/builders/**.v'

jobs:
  check-error-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 121
    env:
      VFLAGS: -cc tcc -no-retry-compilation
    steps:
      - uses: actions/checkout@v4
      - name: Build v
        run: make && ./v symlink
      - name: Check compilation failure
        run: echo 'invalid code' > invalid_code.v && v run invalid_code.v
